### ISSUE TITLE
Map (more) Canto data to Neos

### ISSUE THREAD

**Issue by kdambekalns** [flownative/neos-canto#17]
Canto offers tags, keywords, categories, folders and custom fields to structure assets. Those should be usable in Neos.

My take on a possibe configuration is this:

```yaml
Flownative:
  Canto:
    mapping:
      # map "Custom Fields" from Canto to Neos
      customFields:
        # Foo Bar Baz                    # the name in Canto, for readbility
        'meta_multichoice_0':            # the id in anto
          asAssetCollection: false       # map to an asset collection named after the field
          valuesAsTags: false            # map field values to Neos tags; if true an asset is assigned a tag corresponding to the value, if false any asset "having the field" is in the collection
          include: []                    # only include the listed field values as tags
          exclude: []                    # exclude the listed field values as tags
      # map Canto tags to Neos Tags
      tags:
        enabled: false
        include: []                      # only include the listed tags
        exclude: []                      # exclude the listed tags
      # map Canto keywords to Neos
      keywords:
        asTags: false
        groupInCollection: 'Keywords'
        include: []                      # only include the listed keywords
        exclude: []                      # exclude the listed keywords
      # map Canto folders to Neos
      folders:
        enabled: false
        asAssetCollections: false        # map to an asset collections named after the folders
        asTags: false                    # map to tags named after the folders
        levels: 1                        # if more than 1 nested folders will be mapped to names ("Parent / Child")
        include: []                      # only include the listed folders
        exclude: []                      # exclude the listed folders
      # map Canto categories to Neos
      categories:
        enabled: false
        asAssetCollections: false        # map to an asset collections named after the categories
        asTags: false                    # map to tags named after the categories
        include: []                      # only include the listed categories
        exclude: []                      # exclude the listed categories
```

I'd need to check if the custom fied mapping works for all possible types and if we need to handle this on the Neos side at all (or leave it to the admin to only map usable custom fields).

The configuration shown above is "future-proof", the options can be implemented as needed. And when Neos evolves (e.g. gets support for folders), that can be implemented without breaking the configuration or causing unneeded confusion.)

**Comment by kdambekalns** [comment]
I just realized that Canto has no "categories" concept, "Kategorie" is just the term the German documentation uses for "keyword." 🤦‍♂️

**Comment by danielkestler** [comment]
Hi @kdambekalns,

what do you think about an inversed concept in the mapping configuration for higher flexibility:

```yaml
Flownative:
  Canto:
    mapping:
      # map Canto fields to Neos tags
      tags:
        fields: ['tags']
        include: []
        exclude: ['Untagged']
      # map Canto fields to Neos asset collections
      assetCollections:
        fields: ['meta_multichoice_0.keyword', 'keywords']
        include: []
        exclude: []
```

... just an idea.
